### ISSUE TITLE
pantheon.sh is basically empty

### ISSUE THREAD

**Issue by koesherbacon** [Psyringe/PantheonPythonInstaller#1]
I just wanted you to know that the pantheon.sh bash file is basically empty.  Here is what's inside:
```
#! /bin/bash
echo "Hello world!"
```

Gunna try the python script now, but since you said the bash one was better I thought you'd like to know that there's nothing in it.

**Comment by Psyringe** [comment]
I know. It's a dummu file, just forget it. I should've put a warning or something.
